### ISSUE TITLE
Duplicate entity issues when bootstrapping a node

### ISSUE THREAD

**Issue by RSTJNII** [rackspace-cookbooks/rackspace_cloudmonitoring#22]
While trying to bootstrap a node using "knife rackspace" a duplicate entity was created.  This resulted in convergence failure:

```
[2014-03-25T04:10:11+00:00] ERROR: [HTTP 400 | <Snip ID> ] rackspace_cloudmonitoring_entity[<Snip ID>] (rackspace_cloudmonitoring::monitors line 27) had an error: Fog::Rackspace::Monitoring::BadRequest: [HTTP 400 | <Snip ID>] Cardinality constraint violation - Key already exists with duplicate value. - Key already exists with duplicate value.
 [2014-03-25T04:10:11+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Removing the duplicate entity by hand eliminated the error.  The duplicate was made by Chef.  It is unknown if the automatically generated entity existed when the initial Chef convergence ran.

**Comment by halfshellhero** [comment]
*bump*

From what I've gathered on this, the problem was introduced when our internal automation began creating MaaS entities for any server created at RAX.  What appears to be happening is that sometimes the cookbook is run before internal automation has had a chance to create the entity.  While the entity will eventually be created, if this cookbook is run prior, it will create the entity if it doesn't exist yet:

https://github.com/rackspace-cookbooks/rackspace_cloudmonitoring/blob/master/libraries/entity_hwrp.rb#L143

What this is causing is that chef creates an entity; then our internal automation creates another.  The monitoring set up via the cookbook then sets up all checks on it's own entity and will result in false alerts when the server is deleted as there is nothing I can see that cleans these entities up.

**Comment by halfshellhero** [comment]
IMHO we should not be creating entities at all if our internal automation is going to do so for any newly created server at RAX.  We should wait for the entity to exist and then attach monitoring to it.

**Comment by martinb3** [comment]
It could be cool if our internal automation didn't mark a server as ready until all build automation was complete. It feels like a race condition that could change out from under us.

**Comment by trappar** [comment]
Yeah I have had to build delays into my testing process so I don't run into things like errors due to the apt cache locked by internal automation.

**Comment by halfshellhero** [comment]
Not sure if I'm making my point clear.  I don't believe this cookbook should create an entity at all (or at least have the ability to toggle that on/off).  Knowing that our internal automation will indeed create an entity, we should be using that one as there is additional logic built in to help clean up when servers are deleted.

**Comment by martinb3** [comment]
Moved to https://github.com/rackspace-cookbooks/rackspace_monitoring/issues/16.
